# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'doc'
        repository: 'satishkona/multi'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: push image to docker hub
      inputs:
        containerRegistry: 'doc'
        repository: 'satishkona/multi'
        command: 'push'
        tags: |
          $(Build.BuildId)
          latest
    - task: CopyFiles@2
      displayName: copy files
      inputs:
        SourceFolder: 'k8s-manifest'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)'

- stage: artifact
  displayName: artifact
  jobs:
  - job: artifact
    displayName: artifact
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: PublishBuildArtifacts@1
        displayName: publish artifact
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'